### ISSUE TITLE
As an analyst, I want to navigate between flagged records, in order to find records more quickly.

### ISSUE THREAD

**Issue by pressacco** [BlueDotBrigade/weevil#211]
Acceptance criteria:
- [ ] Go to next flagged record 
- [ ] Go to previous flagged record

**Comment by OrbitThree** [comment]
Can now navigate between records that have been `Flagged` by an _analyzer_ using:

- previous flagged record : `Control+Shift+Alt` and `-` 
- next flagged record : `Control+Shift+Alt` and `+`
