### ISSUE TITLE
As an analyst, I want to navigate between records with comments, in order to find records more quickly.

### ISSUE THREAD

**Issue by pressacco** [BlueDotBrigade/weevil#212]
Acceptance criteria:
- [ ] Go to next record /w comment 
- [ ] Go to previous record /w comment

**Comment by OrbitThree** [comment]
Can now navigate between records with _comments_ using:

- Previous comment  : `Ctrl+Shift+Minus`
- Next comment  : `Ctrl+Shift+Plus`
