### ISSUE TITLE
Create basic framework "the glue" to be able to click the `Open` button using FlaUi.

### ISSUE THREAD

**Issue by Pressacco** [BlueDotBrigade/weevil#322]
# Acceptance Criteria

- [ ] Log reported errors
- [ ] Manage Basic Configuration
- [ ] Come up with simple mechanism to manage references to Weevil UI controls
- [ ] Test: starts Weevil & clicks `Open` button
- [ ] Print the UI control tree when a test run begins
   - [Recursively Assert All Properties Are Non-null Using Reflection][A]

# History

Over the years a number of articles have been published on the topic of automated testing using an application's UI. For example: 

- [Using BDD with SpecFlow, WPF and White][SpecFlowWpfAndWhite]
    - Published 2010, by Marcus Hammarberg.
    - White framework was the predecessor of [FlaUi][FlaUiReadMe]
- [Automated UI Testing of Visual Studio][AutomatedUiTesting]
    - Published 2019 by EasyUiTesting.com

# Open-Source Libraries

- **Aug 2011**: According to the [ReadMe.md][CucumberReadMe] history, _Cucumber_'s _GitHub_ repository was created.
    - https://github.com/TestStack/White
- **Sep 2012**: According to the [ReadMe.md][TestStackReadMe] history, _White_'s _GitHub_ repository was created.
   - https://github.com/TestStack/White
- **Mar 2015**: According to the [ReadMe.md][SpecFlowReadMe] history, _SpecFlow_'s _GitHub_ repository was created.
    - https://github.com/SpecFlowOSS/SpecFlow
- **Oct 2016**: According to the [ReadMe.md][FlaUiReadMe] history, _FlaUi_'s _GitHub_ repository was created.
   - https://github.com/FlaUI/FlaUI
- **Dec 2019**: The _White_ framework was officially flagged as _Deprecated_.

[CucumberReadMe]: https://github.com/cucumber/cucumber-jvm/blob/main/README.md
[SpecFlowReadMe]: https://github.com/SpecFlowOSS/SpecFlow/blob/master/README.md
[TestStackReadMe]: https://github.com/TestStack/White/blob/master/README.md
[FlaUiReadMe]: https://github.com/FlaUI/FlaUI/blob/master/README.md

[SpecFlowWpfAndWhite]: http://www.marcusoft.net/2010/08/using-bdd-with-specflow-wpf-and-white_14.html
[AutomatedUiTesting]: https://easyuitesting.com/automated-ui-testing-of-visual-studio/

[A]: https://chrisfrew.in/blog/recursively-assert-all-properties-are-non-null-with-reflection/

**Comment by BlueDotBrigadeFounder** [comment]
# Implementation Details

- The automation code will be organized into layers as per SpecFlow's recommendation:
   -  SpecFlow: [Using Page Object (POM) Model][SpecFlowPom]

[SpecFlowPom]: https://docs.specflow.org/projects/specflow/en/latest/Guides/PageObjectModel.html

**Comment by BlueDotBrigadeFounder** [comment]
# Status Update

While the original intent of _Milestone 2.11_ was to guarantee application stability through UI testing using [SpecFlow](https://specflow.org) and [FlaUi](https://github.com/FlaUI/FlaUI)... it has been decided that the scope would be scaled back to:
- complete requirement coverage at the `ViewModel` level
- using [SpecFlow](https://specflow.org) and [Cucumber](https://automationpanda.com/tag/cucumber)
