### ISSUE TITLE
Upgrade NuGet packages.

### ISSUE THREAD

**Issue by Pressacco** [BlueDotBrigade/weevil#336]
Be sure to update app packages including: 
- [ ] Datenlokator

**Comment by snakefoot** [comment]
Notice that this logic can fail with NLog v5:
```c#
			case LogSeverityType.Trace:
					LogWriter.Log(
						typeof(NLogWriter),
						LogWriter.ForTraceEvent().Message(message).Properties(properties).LogEvent);
```
Beause `.LogEvent`-property can return `null` when the LogLevel.Trace is not enabled. And one is not allowed to pass LogEventInfo == null into `Logger.Log(...)`-method, so now it will fail when LogLevel is not enabled.

I suggest you change into this instead:

```c#
public void Write(LogSeverityType severity, string message, IDictionary metadata)
{
     var logLevel = ResolveLogLevel(severity);
     var properties = ResolveProperties(metadata);
     var logEvent = LogWriter.ForLogEvent(logLevel).Message(message).Properties(properties).LogEvent;
     if (logEvent != null)
             LogWriter.Log(typeof(NLogWriter), logEvent);
}

public void Write(LogSeverityType severity, Exception exception, string message, IDictionary metadata)
{
     var logLevel = ResolveLogLevel(severity);
     var properties = ResolveProperties(metadata);
     var logEvent = LogWriter.ForLogEvent(logLevel).Exception(exception).Message(message).Properties(properties).LogEvent;
     if (logEvent != null)
             LogWriter.Log(typeof(NLogWriter), logEvent);
}

private NLog.LogLevel ResolveLogLevel(LogSeverityType severity)
{
     switch (severity)
     {
          case LogSeverityType.Trace: return NLog.LogLevel.Trace;
          case LogSeverityType.Information: return NLog.LogLevel.Info;
          case LogSeverityType.Warning: return NLog.LogLevel.Warn;
          case LogSeverityType.Error: return NLog.LogLevel.Error;
          case LogSeverityType.Critical: return NLog.LogLevel.Fatal;
          case LogSeverityType.Debug:
          default:
              return NLog.LogLevel.Debug;
     }
}
```

Notice to make MetaData continue to support HashTable, then I suggest the following method:

```c#
private IEnumerable<KeyValuePair<string, object>> ResolveProperties(IDictionary dictionary)
{
         if (dictionary?.Count > 0)
         {
              if (dictionary is IEnumerable<KeyValuePair<string, object>> properties)
                    return properties;
              else 
                    return YieldDictionaryProperties(dictionary);
         }
         return NoProperties;
}

private IEnumerable<KeyValuePair<string, object>> YieldDictionaryProperties(IDictionary dictionary)
{
       foreach (DictionaryEntry item in dictionary)
           yield new KeyValuePair(item.Key.ToString(), item.Value);
}
```

When next version of NLog v5 is released then a new `Log(Type wrapperType)`-method is added so you can do this:

```c#
     var logLevel = ResolveLogLevel(severity);
     var properties = ResolveProperties(metadata);
     LogWriter.ForLogEvent(logLevel).Exception(exception).Message(message).Properties(properties).Log(typeof(NLogWriter));
```

**Comment by Pressacco** [comment]
# Post Sharp Compiler Issues

## The Problem

GitHub action would randomly fail with the following error:

- > error PS0242: License error. No valid license key has been installed. To register a license key, see https://doc.postsharp.net/deploying-keys.

A support ticket was created:
- [Random licensing errors (PS0242)](https://tp.postsharp.net/helpdesk/request/31022-random-licensing-errors-ps0242)

## Analysis

- no AssemblyName + no TargetName: 
	- Executable: BlueDotBrigade.Weevil.Gui.exe
	- AssemblyIL: BlueDotBrigade.Weevil.Gui, PublicKeyToken=null
	- BuildStatus: PostSharp works on GitHub
- AssemblyName explicitly defined as `BlueDotBrigade.Weevil.Gui`, no TargetName
	- Executable: BlueDotBrigade.Weevil.Gui.exe
	- BuildStatus: PostSharp works on GitHub
- AssemblyName explicitly defined as `WeevilGui`, no TargetName
	- Executable: WeevilGui.exe
	- AssemblyIL: WeevilGui, PublicKeyToken=null
	- BuildStatus: compiler error
		- error PS0242: License error. No valid license key has been installed. To register a license key, see https://doc.postsharp.net/deploying-keys.
- no AssemblyName, TargetName=WeevilGui
	- GUI `*.csproj` won't compile locally due to namespace error:
		- The tag 'SeverityToBackgroundConverter' does not exist in XML namespace 'clr-namespace:BlueDotBrigade.Weevil.Gui.Converters'
			- xmlns:converters="clr-namespace:BlueDotBrigade.Weevil.Gui.Converters"
		- PostSharp warned about "handling a few consequences in XAML" when specifying the `TargetName`
		- Note: IntelliSense that the `TargetName` element is no longer supported in .NET core project file
			- This element is not listed in the list of options when editing `*.csproj`

## Solutions

1. AssemblyName=BlueDotBrigade.Weevil.Gui
	- Adv: Follows .NET methodology, no hacky workaround.
	- Adv: No PostSharp PS0242 licensing errors.
	- Dis: the intent was to have the following in the `Bin` directory
		- WeevilGui.exe
		- WeevilCli.exe
2. Ask for license that is specific to `WeevilGui.exe`
	- Dis: This won't work when using PostSharp in the other Weevil assemblies.
3. PostBuild event: rename output to WeevilGui.exe
	- Dis: This is a hacky workaround... what other headaches will this create? 
		- Installer issues?

**Comment by Pressacco** [comment]
# NLog v5: NullReferenceException

## Background

Many thanks to @snakefoot who pointed out that:

- > Beause .LogEvent-property can return null when the LogLevel.Trace is not enabled (skips allocation when not needed). And one is not allowed to pass LogEventInfo == null into Logger.Log(...)-method, so now it will throw when LogLevel is not enabled.

For more information, see Pull Request #352 [comment](https://github.com/BlueDotBrigade/weevil/pull/352#issuecomment-1236166585).

## Implementation Details

- After the change, Weevil did not create log entries because the `LogLevel` had not been set properly.

## Additional Reading

- NLog documentation
   - [NLog Config](https://nlog-project.org/config/)
- [Configure NLog in .NET Core Application](https://programmingcsharp.com/nlog-net-core/)

**Comment by snakefoot** [comment]
Notice when renaming the assembly 9f83e5b5b338b6ae40d1962095545aafe534a288 then one should also have renamed to `BlueDotBrigade.Weevil.Gui.exe.nlog`

So it is not because of NLog5 that it stopped loading. But renaming to nlog.config 3eaec1b4fb1f7790fba364bae755bd1441a3ccb4  will also make it work independent of exe-file-name.
